// Danh mục tiền tệ ISO 4217 hiện hành, đồng bộ từ SIX ngày 01/01/2026.
export type CurrencyMetadata = {
  code: string;
  name: string;
  country: string;
};

export const CURRENCIES: CurrencyMetadata[] = [
  { code: 'VND', name: "Việt Nam đồng", country: "Việt Nam" },
  { code: 'USD', name: "Đô la Mỹ", country: "Hoa Kỳ" },
  { code: 'EUR', name: "Euro", country: "Khu vực đồng Euro" },
  { code: 'AUD', name: "Đô la Úc", country: "Úc" },
  { code: 'JPY', name: "Yên Nhật", country: "Nhật Bản" },
  { code: 'GBP', name: "Bảng Anh", country: "Vương quốc Anh" },
  { code: 'SGD', name: "Đô la Singapore", country: "Singapore" },
  { code: 'THB', name: "Baht Thái", country: "Thái Lan" },
  { code: 'CNY', name: "Nhân dân tệ", country: "Trung Quốc" },
  { code: 'HKD', name: "Đô la Hồng Kông", country: "Hồng Kông" },
  { code: 'KRW', name: "Won Hàn Quốc", country: "Hàn Quốc" },
  { code: 'CAD', name: "Đô la Canada", country: "Canada" },
  { code: 'CHF', name: "Franc Thụy Sĩ", country: "Thụy Sĩ" },
  { code: 'NZD', name: "Đô la New Zealand", country: "New Zealand" },
  { code: 'TWD', name: "Đô la Đài Loan", country: "Đài Loan" },
  { code: 'MYR', name: "Ringgit Malaysia", country: "Malaysia" },
  { code: 'IDR', name: "Rupiah Indonesia", country: "Indonesia" },
  { code: 'PHP', name: "Peso Philippines", country: "Philippines" },
  { code: 'LAK', name: "Kip Lào", country: "Lào" },
  { code: 'KHR', name: "Riel Campuchia", country: "Campuchia" },
  { code: 'AED', name: "UAE Dirham", country: "UNITED ARAB EMIRATES (THE)" },
  { code: 'AFN', name: "Afghani", country: "AFGHANISTAN" },
  { code: 'ALL', name: "Lek", country: "ALBANIA" },
  { code: 'AMD', name: "Armenian Dram", country: "ARMENIA" },
  { code: 'AOA', name: "Kwanza", country: "ANGOLA" },
  { code: 'ARS', name: "Argentine Peso", country: "ARGENTINA" },
  { code: 'AWG', name: "Aruban Florin", country: "ARUBA" },
  { code: 'AZN', name: "Azerbaijan Manat", country: "AZERBAIJAN" },
  { code: 'BAM', name: "Convertible Mark", country: "BOSNIA AND HERZEGOVINA" },
  { code: 'BBD', name: "Barbados Dollar", country: "BARBADOS" },
  { code: 'BDT', name: "Taka", country: "BANGLADESH" },
  { code: 'BHD', name: "Bahraini Dinar", country: "BAHRAIN" },
  { code: 'BIF', name: "Burundi Franc", country: "BURUNDI" },
  { code: 'BMD', name: "Bermudian Dollar", country: "BERMUDA" },
  { code: 'BND', name: "Brunei Dollar", country: "BRUNEI DARUSSALAM" },
  { code: 'BOB', name: "Boliviano", country: "BOLIVIA (PLURINATIONAL STATE OF)" },
  { code: 'BRL', name: "Brazilian Real", country: "BRAZIL" },
  { code: 'BSD', name: "Bahamian Dollar", country: "BAHAMAS (THE)" },
  { code: 'BTN', name: "Ngultrum", country: "BHUTAN" },
  { code: 'BWP', name: "Pula", country: "BOTSWANA" },
  { code: 'BYN', name: "Belarusian Ruble", country: "BELARUS" },
  { code: 'BZD', name: "Belize Dollar", country: "BELIZE" },
  { code: 'CDF', name: "Congolese Franc", country: "CONGO (THE DEMOCRATIC REPUBLIC OF THE)" },
  { code: 'CLP', name: "Chilean Peso", country: "CHILE" },
  { code: 'COP', name: "Colombian Peso", country: "COLOMBIA" },
  { code: 'CRC', name: "Costa Rican Colon", country: "COSTA RICA" },
  { code: 'CUP', name: "Cuban Peso", country: "CUBA" },
  { code: 'CVE', name: "Cabo Verde Escudo", country: "CABO VERDE" },
  { code: 'CZK', name: "Czech Koruna", country: "CZECHIA" },
  { code: 'DJF', name: "Djibouti Franc", country: "DJIBOUTI" },
  { code: 'DKK', name: "Danish Krone", country: "DENMARK + 2 quốc gia/vùng lãnh thổ" },
  { code: 'DOP', name: "Dominican Peso", country: "DOMINICAN REPUBLIC (THE)" },
  { code: 'DZD', name: "Algerian Dinar", country: "ALGERIA" },
  { code: 'EGP', name: "Egyptian Pound", country: "EGYPT" },
  { code: 'ERN', name: "Nakfa", country: "ERITREA" },
  { code: 'ETB', name: "Ethiopian Birr", country: "ETHIOPIA" },
  { code: 'FJD', name: "Fiji Dollar", country: "FIJI" },
  { code: 'FKP', name: "Falkland Islands Pound", country: "FALKLAND ISLANDS (THE) [MALVINAS]" },
  { code: 'GEL', name: "Lari", country: "GEORGIA" },
  { code: 'GHS', name: "Ghana Cedi", country: "GHANA" },
  { code: 'GIP', name: "Gibraltar Pound", country: "GIBRALTAR" },
  { code: 'GMD', name: "Dalasi", country: "GAMBIA (THE)" },
  { code: 'GNF', name: "Guinean Franc", country: "GUINEA" },
  { code: 'GTQ', name: "Quetzal", country: "GUATEMALA" },
  { code: 'GYD', name: "Guyana Dollar", country: "GUYANA" },
  { code: 'HNL', name: "Lempira", country: "HONDURAS" },
  { code: 'HTG', name: "Gourde", country: "HAITI" },
  { code: 'HUF', name: "Forint", country: "HUNGARY" },
  { code: 'ILS', name: "New Israeli Sheqel", country: "ISRAEL" },
  { code: 'INR', name: "Indian Rupee", country: "BHUTAN + 1 quốc gia/vùng lãnh thổ" },
  { code: 'IQD', name: "Iraqi Dinar", country: "IRAQ" },
  { code: 'IRR', name: "Iranian Rial", country: "IRAN (ISLAMIC REPUBLIC OF)" },
  { code: 'ISK', name: "Iceland Krona", country: "ICELAND" },
  { code: 'JMD', name: "Jamaican Dollar", country: "JAMAICA" },
  { code: 'JOD', name: "Jordanian Dinar", country: "JORDAN" },
  { code: 'KES', name: "Kenyan Shilling", country: "KENYA" },
  { code: 'KGS', name: "Som", country: "KYRGYZSTAN" },
  { code: 'KMF', name: "Comorian Franc", country: "COMOROS (THE)" },
  { code: 'KPW', name: "North Korean Won", country: "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)" },
  { code: 'KWD', name: "Kuwaiti Dinar", country: "KUWAIT" },
  { code: 'KYD', name: "Cayman Islands Dollar", country: "CAYMAN ISLANDS (THE)" },
  { code: 'KZT', name: "Tenge", country: "KAZAKHSTAN" },
  { code: 'LBP', name: "Lebanese Pound", country: "LEBANON" },
  { code: 'LKR', name: "Sri Lanka Rupee", country: "SRI LANKA" },
  { code: 'LRD', name: "Liberian Dollar", country: "LIBERIA" },
  { code: 'LSL', name: "Loti", country: "LESOTHO" },
  { code: 'LYD', name: "Libyan Dinar", country: "LIBYA" },
  { code: 'MAD', name: "Moroccan Dirham", country: "MOROCCO + 1 quốc gia/vùng lãnh thổ" },
  { code: 'MDL', name: "Moldovan Leu", country: "MOLDOVA (THE REPUBLIC OF)" },
  { code: 'MGA', name: "Malagasy Ariary", country: "MADAGASCAR" },
  { code: 'MKD', name: "Denar", country: "NORTH MACEDONIA" },
  { code: 'MMK', name: "Kyat", country: "MYANMAR" },
  { code: 'MNT', name: "Tugrik", country: "MONGOLIA" },
  { code: 'MOP', name: "Pataca", country: "MACAO" },
  { code: 'MRU', name: "Ouguiya", country: "MAURITANIA" },
  { code: 'MUR', name: "Mauritius Rupee", country: "MAURITIUS" },
  { code: 'MVR', name: "Rufiyaa", country: "MALDIVES" },
  { code: 'MWK', name: "Malawi Kwacha", country: "MALAWI" },
  { code: 'MXN', name: "Mexican Peso", country: "MEXICO" },
  { code: 'MZN', name: "Mozambique Metical", country: "MOZAMBIQUE" },
  { code: 'NAD', name: "Namibia Dollar", country: "NAMIBIA" },
  { code: 'NGN', name: "Naira", country: "NIGERIA" },
  { code: 'NIO', name: "Cordoba Oro", country: "NICARAGUA" },
  { code: 'NOK', name: "Norwegian Krone", country: "BOUVET ISLAND + 2 quốc gia/vùng lãnh thổ" },
  { code: 'NPR', name: "Nepalese Rupee", country: "NEPAL" },
  { code: 'OMR', name: "Rial Omani", country: "OMAN" },
  { code: 'PAB', name: "Balboa", country: "PANAMA" },
  { code: 'PEN', name: "Sol", country: "PERU" },
  { code: 'PGK', name: "Kina", country: "PAPUA NEW GUINEA" },
  { code: 'PKR', name: "Pakistan Rupee", country: "PAKISTAN" },
  { code: 'PLN', name: "Zloty", country: "POLAND" },
  { code: 'PYG', name: "Guarani", country: "PARAGUAY" },
  { code: 'QAR', name: "Qatari Rial", country: "QATAR" },
  { code: 'RON', name: "Romanian Leu", country: "ROMANIA" },
  { code: 'RSD', name: "Serbian Dinar", country: "SERBIA" },
  { code: 'RUB', name: "Russian Ruble", country: "RUSSIAN FEDERATION (THE)" },
  { code: 'RWF', name: "Rwanda Franc", country: "RWANDA" },
  { code: 'SAR', name: "Saudi Riyal", country: "SAUDI ARABIA" },
  { code: 'SBD', name: "Solomon Islands Dollar", country: "SOLOMON ISLANDS" },
  { code: 'SCR', name: "Seychelles Rupee", country: "SEYCHELLES" },
  { code: 'SDG', name: "Sudanese Pound", country: "SUDAN (THE)" },
  { code: 'SEK', name: "Swedish Krona", country: "SWEDEN" },
  { code: 'SHP', name: "Saint Helena Pound", country: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA" },
  { code: 'SLE', name: "Leone", country: "SIERRA LEONE" },
  { code: 'SOS', name: "Somali Shilling", country: "SOMALIA" },
  { code: 'SRD', name: "Surinam Dollar", country: "SURINAME" },
  { code: 'SSP', name: "South Sudanese Pound", country: "SOUTH SUDAN" },
  { code: 'STN', name: "Dobra", country: "SAO TOME AND PRINCIPE" },
  { code: 'SVC', name: "El Salvador Colon", country: "EL SALVADOR" },
  { code: 'SYP', name: "Syrian Pound", country: "SYRIAN ARAB REPUBLIC" },
  { code: 'SZL', name: "Lilangeni", country: "ESWATINI" },
  { code: 'TJS', name: "Somoni", country: "TAJIKISTAN" },
  { code: 'TMT', name: "Turkmenistan New Manat", country: "TURKMENISTAN" },
  { code: 'TND', name: "Tunisian Dinar", country: "TUNISIA" },
  { code: 'TOP', name: "Pa’anga", country: "TONGA" },
  { code: 'TRY', name: "Turkish Lira", country: "TÜRKİYE" },
  { code: 'TTD', name: "Trinidad and Tobago Dollar", country: "TRINIDAD AND TOBAGO" },
  { code: 'TZS', name: "Tanzanian Shilling", country: "TANZANIA, UNITED REPUBLIC OF" },
  { code: 'UAH', name: "Hryvnia", country: "UKRAINE" },
  { code: 'UGX', name: "Uganda Shilling", country: "UGANDA" },
  { code: 'UYU', name: "Peso Uruguayo", country: "URUGUAY" },
  { code: 'UYW', name: "Unidad Previsional", country: "URUGUAY" },
  { code: 'UZS', name: "Uzbekistan Sum", country: "UZBEKISTAN" },
  { code: 'VED', name: "Bolívar Soberano", country: "VENEZUELA (BOLIVARIAN REPUBLIC OF)" },
  { code: 'VES', name: "Bolívar Soberano", country: "VENEZUELA (BOLIVARIAN REPUBLIC OF)" },
  { code: 'VUV', name: "Vatu", country: "VANUATU" },
  { code: 'WST', name: "Tala", country: "SAMOA" },
  { code: 'XAF', name: "CFA Franc BEAC", country: "CAMEROON + 5 quốc gia/vùng lãnh thổ" },
  { code: 'XCD', name: "East Caribbean Dollar", country: "ANGUILLA + 7 quốc gia/vùng lãnh thổ" },
  { code: 'XCG', name: "Caribbean Guilder", country: "CURAÇAO + 1 quốc gia/vùng lãnh thổ" },
  { code: 'XOF', name: "CFA Franc BCEAO", country: "BENIN + 7 quốc gia/vùng lãnh thổ" },
  { code: 'XPF', name: "CFP Franc", country: "FRENCH POLYNESIA + 2 quốc gia/vùng lãnh thổ" },
  { code: 'YER', name: "Yemeni Rial", country: "YEMEN" },
  { code: 'ZAR', name: "Rand", country: "LESOTHO + 2 quốc gia/vùng lãnh thổ" },
  { code: 'ZMW', name: "Zambian Kwacha", country: "ZAMBIA" },
  { code: 'ZWG', name: "Zimbabwe Gold", country: "ZIMBABWE" },
];

const currencyByCode = new Map(CURRENCIES.map((currency) => [currency.code, currency]));

export function getCurrencyMetadata(code: string): CurrencyMetadata {
  const normalizedCode = String(code ?? '').toUpperCase();
  return currencyByCode.get(normalizedCode) ?? {
    code: normalizedCode,
    name: normalizedCode,
    country: 'Chưa cập nhật',
  };
}

export const currencyCodes = CURRENCIES.map((currency) => currency.code);

export const currencyOptions = CURRENCIES.map((currency) => ({
  value: currency.code,
  label: `${currency.code} - ${currency.name} - ${currency.country}`,
}));
