import {
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  CheckSquareOutlined,
  DashboardOutlined,
  DollarOutlined,
  FieldTimeOutlined,
  FileSearchOutlined,
  MoneyCollectOutlined,
  SafetyCertificateOutlined,
  ShopOutlined,
  TransactionOutlined,
  UserOutlined,
  UserSwitchOutlined,
  WalletOutlined,
} from '@ant-design/icons';
import type { AppMenuItem } from '@/shared/types/navigation';

export const navigationItems: AppMenuItem[] = [
  {
    key: '/dashboard',
    icon: <DashboardOutlined />,
    label: 'Dashboard',
    path: '/dashboard',
  },
  {
    key: '/shift-management/active-shift',
    icon: <FieldTimeOutlined />,
    label: 'Ca Làm Việc',
    path: '/shift-management/active-shift',
    allowedRoles: ['branch'],
    requiredPermission: 'shift.open',
  },
  {
    key: '/transactions',
    icon: <TransactionOutlined />,
    label: 'Giao Dịch',
    path: '/transactions',
    requiredPermission: 'transaction.view',
  },
  {
    key: 'branch-management',
    icon: <ShopOutlined />,
    label: 'Chi Nhánh',
    children: [
      { key: '/branch-management/monitoring', label: 'Theo dõi chi nhánh', path: '/branch-management/monitoring', allowedRoles: ['director', 'accountant'], requiredPermission: 'fund.view' },
    ],
    allowedRoles: ['director', 'accountant'],
    requiredPermission: 'fund.view',
  },
  {
    key: 'fund',
    icon: <WalletOutlined />,
    label: 'Quỹ',
    children: [
      { key: '/fund-management/central-fund', label: 'Quỹ Chung', path: '/fund-management/central-fund', allowedRoles: ['director', 'accountant', 'auditor'], requiredPermission: 'fund.view' },
      { key: '/cash-count/branch', label: 'Kiểm Quỹ', path: '/cash-count/branch', requiredPermission: 'shift.close' },
      { key: '/cash-count/central', label: 'Kiểm Quỹ Tổng', path: '/cash-count/central', allowedRoles: ['director', 'accountant', 'auditor'], requiredPermission: 'fund.view' },
    ],
    requiredPermission: 'fund.view',
  },
  {
    key: 'exchange-rate',
    icon: <DollarOutlined />,
    label: 'Tỷ Giá',
    children: [
      { key: '/exchange-rate', label: 'Bảng tỷ giá', path: '/exchange-rate', requiredPermission: 'exchange_rate.view' },
      { key: '/exchange-rate/approval', label: 'Duyệt tỷ giá', path: '/exchange-rate/approval', requiredPermission: 'exchange_rate.view' },
      { key: '/exchange-rate/history', label: 'Lịch sử tỷ giá', path: '/exchange-rate/history', requiredPermission: 'exchange_rate.view' },
    ],
    requiredPermission: 'exchange_rate.view',
  },
  {
    key: 'fund-transfer',
    icon: <UserSwitchOutlined />,
    label: 'Tiếp Quỹ',
    children: [
      { key: '/fund-transfer', label: 'Tổng quan', path: '/fund-transfer', requiredPermission: 'fund.transfer' },
      { key: '/fund-transfer/workspace', label: 'Điều chuyển vốn', path: '/fund-transfer/workspace', requiredPermission: 'fund.transfer' },
    ],
    allowedRoles: ['director', 'accountant'],
    requiredPermission: 'fund.transfer',
  },
  {
    key: 'debt-management',
    icon: <MoneyCollectOutlined />,
    label: 'Công Nợ',
    children: [
      { key: '/debt-management/debt-list', label: 'Danh sách', path: '/debt-management/debt-list', requiredPermission: 'debt.view' },
      { key: '/debt-management/settlement', label: 'Giải quyết công nợ', path: '/debt-management/settlement', requiredPermission: 'debt.view' },
    ],
    allowedRoles: ['director', 'accountant', 'auditor'],
    requiredPermission: 'debt.view',
  },
  {
    key: 'bank-management',
    icon: <BankOutlined />,
    label: 'Ngân Hàng',
    children: [
      { key: '/bank-management/accounts', label: 'Tài khoản', path: '/bank-management/accounts', requiredPermission: 'bank.view' },
    ],
    allowedRoles: ['director', 'accountant', 'auditor'],
    requiredPermission: 'bank.view',
  },
  {
    key: '/reconciliation',
    icon: <CheckSquareOutlined />,
    label: 'Đối Chiếu',
    path: '/reconciliation',
    allowedRoles: ['director', 'accountant', 'auditor'],
  },
  {
    key: '/reports',
    icon: <BarChartOutlined />,
    label: 'Báo Cáo',
    path: '/reports',
    allowedRoles: ['director', 'accountant', 'auditor'],
    requiredPermission: 'report.view',
  },
  {
    key: '/audit-log',
    icon: <AuditOutlined />,
    label: 'Audit Log',
    path: '/audit-log',
    allowedRoles: ['director', 'accountant', 'auditor'],
    requiredPermission: 'audit_log.view',
  },
  {
    key: 'administration',
    icon: <SafetyCertificateOutlined />,
    label: 'Quản Trị',
    children: [
      { key: '/user-management/users', label: 'Người dùng', path: '/user-management/users', icon: <UserOutlined /> },
      { key: '/user-management/permissions', label: 'Phân quyền', path: '/user-management/permissions', icon: <FileSearchOutlined /> },
    ],
    allowedRoles: ['director'],
  },
];
