import {
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  CheckSquareOutlined,
  DashboardOutlined,
  DollarOutlined,
  FieldTimeOutlined,
  FileSearchOutlined,
  MoneyCollectOutlined,
  SafetyCertificateOutlined,
  ShopOutlined,
  TransactionOutlined,
  UserOutlined,
  WalletOutlined,
} from '@ant-design/icons';
import type { AppMenuItem } from '@/shared/types/navigation';

export const navigationItems: AppMenuItem[] = [
  {
    key: '/dashboard',
    icon: <DashboardOutlined />,
    label: 'Dashboard',
    path: '/dashboard',
  },
  {
    key: '/shift-management/active-shift',
    icon: <FieldTimeOutlined />,
    label: 'Ca Làm Việc',
    path: '/shift-management/active-shift',
    allowedRoles: ['branch'],
    requiredPermission: 'shift.open',
  },
  {
    key: '/transactions',
    icon: <TransactionOutlined />,
    label: 'Giao Dịch',
    path: '/transactions',
    requiredPermission: 'transaction.view',
  },
  {
    key: '/branch-management/monitoring',
    icon: <ShopOutlined />,
    label: 'Chi Nhánh',
    path: '/branch-management/monitoring',
    allowedRoles: ['director', 'accountant'],
    requiredPermission: 'fund.view',
  },
  {
    key: '/fund-management/central-fund',
    icon: <WalletOutlined />,
    label: 'Quỹ',
    path: '/fund-management/central-fund',
    allowedRoles: ['director', 'accountant', 'auditor'],
    requiredPermission: 'fund.view',
  },
  {
    key: '/fund-management/branch-funds',
    icon: <WalletOutlined />,
    label: 'Quỹ',
    path: '/fund-management/branch-funds',
    allowedRoles: ['branch'],
  },
  {
    key: '/exchange-rate',
    icon: <DollarOutlined />,
    label: 'Tỷ Giá',
    path: '/exchange-rate',
    requiredPermission: 'exchange_rate.view',
  },
  {
    key: '/debt-management',
    icon: <MoneyCollectOutlined />,
    label: 'Công Nợ',
    path: '/debt-management',
    allowedRoles: ['director', 'accountant', 'auditor'],
    requiredPermission: 'debt.view',
  },
  {
    key: '/bank-management/accounts',
    icon: <BankOutlined />,
    label: 'Ngân Hàng',
    path: '/bank-management/accounts',
    allowedRoles: ['director', 'accountant', 'auditor'],
    requiredPermission: 'bank.view',
  },
  {
    key: 'reconciliation',
    icon: <CheckSquareOutlined />,
    label: 'Đối Chiếu',
    children: [
      { key: '/reconciliation', label: 'Đối chiếu quỹ', path: '/reconciliation' },
      { key: '/reconciliation/journal', label: 'Đối chiếu Journal', path: '/reconciliation/journal' },
    ],
    allowedRoles: ['director', 'accountant', 'auditor'],
  },
  {
    key: 'reports',
    icon: <BarChartOutlined />,
    label: 'Báo Cáo',
    children: [
      { key: '/reports', label: 'Tổng quan', path: '/reports', requiredPermission: 'report.view' },
      { key: '/reports/summary', label: 'Báo cáo tổng hợp', path: '/reports/summary', requiredPermission: 'report.view' },
    ],
    allowedRoles: ['director', 'accountant', 'auditor'],
    requiredPermission: 'report.view',
  },
  {
    key: 'audit-log',
    icon: <AuditOutlined />,
    label: 'Audit Log',
    children: [
      { key: '/audit-log', label: 'Tổng quan', path: '/audit-log', requiredPermission: 'audit_log.view' },
      { key: '/audit-log/live', label: 'Nhật ký hệ thống', path: '/audit-log/live', requiredPermission: 'audit_log.view' },
    ],
    allowedRoles: ['director', 'accountant', 'auditor'],
    requiredPermission: 'audit_log.view',
  },
  {
    key: 'administration',
    icon: <SafetyCertificateOutlined />,
    label: 'Quản Trị',
    children: [
      { key: '/user-management/users', label: 'Người dùng', path: '/user-management/users', icon: <UserOutlined /> },
      { key: '/user-management/permissions', label: 'Phân quyền', path: '/user-management/permissions', icon: <FileSearchOutlined /> },
    ],
    allowedRoles: ['director'],
  },
];
